### PR TITLE
Moved API structs from source to header file

### PR DESCRIPTION
**Pull request by mortaas**
The structs for the survive_API is currently defined in the source file. This could have been done intentionally for all I know, but it severely limits your access to libsurvive without these definitions. I have therefore moved these definitions to the header file instead.

### CODE REVIEW

**Comment by jdavidberger** [comment]
These structs are intentionally only defined inside that c file. The idea is it makes it much easier to maintain a consistent api layer if the only pointers you have are [opaque pointers](https://en.m.wikipedia.org/wiki/Opaque_pointer).

The trade off between the simplified api vs the direct api is that the former is more insulated to change and overall has less details to manage. I don't want to lose that. 

However this doesn't necessarily have to mean you don't have access to internal details. We can add accessor functions for basically anything. 

I'm also not against the idea of having an access function for underlying SurviveObject pointers as an "out". It'd serve as a useful point of access for where there aren't accessor functions defined. 

What are you wanting to access? Depending on what you are wanting to do, we can add functionality to get it done and maintain encapsulation.

**Comment by mortaas** [comment]
I had a suspicion that something like encapsulation was the case, it's just the fact that the API features are lacking in its current shape.

As it stands right now; I am currently using:
actx_->ctx
actx_->objects
actx_->object_ct
actx_->poll_mutex
I am probably able to do most of the things I want if you provide accessors to the underlying SurviveContext, SurviveObjects (+ lighthouses) and the ability to lock and unlock the mutex.

**Comment by jdavidberger** [comment]
I've added everything but access to objects. I think with access to the internal structs you probably don't need it; and I want to keep the access to the objects field as that iterator construct. Its in master.

You will have to add a '#define SURVIVE_ENABLE_FULL_API' before the header file inclusion.

It's somewhat annoying, but the idea is that we get the ability to remove and add devices as they come online and to do that safely we either need to swap objects to a linked list, or constantly possibly realloc the list.

In terms of what you are using those underlying fields for, it'd be nice to add accessor functions to get the same functionality without hitting the internals. Can you describe what you are using them for or post / link code that you are writing for it?

**Comment by mortaas** [comment]
Thanks, that's a nice and clean workaround until the API is more developed. The basic (and missing) functionality that I need from the API is tracking status, linear+angular velocity, inputs, events and device class ID. A simple event system/stack for inputs and device changes would suffice. I need to know the controller events to know when to publish inputs in ROS, and an device change event to know when to update my internal list of devices. Perhaps most important is the ability to know the tracking status from the API, as my VIVE setup is still kind of unstable with libsurvive, and I would like to now when I can trust the tracking of a device.

This is how I handle input events for instance:
```
std::queue<int> controller_event_type, controller_device_index;

static void button_process(SurviveObject *so, uint8_t eventType, uint8_t buttonId, uint8_t axis1Id, uint16_t axis1Val, uint8_t axis2Id, uint16_t axis2Val)
{
    survive_default_button_process(so, eventType, buttonId, axis1Id, axis1Val, axis2Id, axis2Val);

    void *ptr = so;

    struct SurviveSimpleContext *actx = (struct SurviveSimpleContext *) so->ctx->user_ptr;
    intptr_t i = (intptr_t) so->user_ptr;

    OGLockMutex(actx->poll_mutex);

    switch(eventType) {
        case BUTTON_EVENT_BUTTON_DOWN :
            controller_device_index.push(i);
            controller_event_type.push(200); // ButtonPress
            break;
        case BUTTON_EVENT_BUTTON_UP :
            controller_device_index.push(i);
            controller_event_type.push(201); // ButtonUnpress
            break;
        case BUTTON_EVENT_AXIS_CHANGED :
            if (axis1Val + axis2Val != 0.) {
                controller_device_index.push(i);
                controller_event_type.push(202); // ButtonTouch
            } else {
                controller_device_index.push(i);
                controller_event_type.push(203); // ButtonUntouch
            }
            break;
        case BUTTON_EVENT_BUTTON_NONE :
            break;
    }

    OGUnlockMutex(actx->poll_mutex);
}


bool ViveInterface::PollNextEvent(int &event_type, int &device_index) {
      /**
     * Returns true if there is any event waiting in the event queue,
     * and also returns the event type and device index of this event.
     * Returns event type VREvent_None (0) and device index k_unTrackedDeviceIndexInvalid (4294967295)
     * if there is no event waiting in the event queue.
     */

    OGLockMutex(actx_->poll_mutex);

    if (!controller_event_type.empty() ) {
        event_type = controller_event_type.front();
        device_index = controller_device_index.front();

        controller_event_type.pop();
        controller_device_index.pop();
    } else {
        event_type = 0;
        device_index = 0xFFFFFFFF;
    }

    OGUnlockMutex(actx_->poll_mutex);

    if (!(event_type == 0 && device_index == 0xFFFFFFFF) ) {
        return true;
    } else {
        return false;
    }
}
```

I am currently pulling the missing data I need directly from the internal data structures, so a more sane approach would be much appreciated.

**Comment by jdavidberger** [comment]
Pushed velocity, button interface additions to master. 

I updated api_example.c to read button events as a demonstration. Right now the only event type is the button events, that can / should be expanded in the future.

Objects for the most part right now are all added at startup. When that changes, there should be an event for add/remove. 

In terms of trusting the output, you shouldn't see poses until the system is pretty sure they are valid. There is definitely some filtering that needs to go in when light packets are dropped, as right now it creates a blip of error. 

When calibration is done, it should then update the lighthouse positions as normal objects, which should tell you when that is finished. Before calibration, nothing should have positions updated at all. Let me know if this isn't working that way. 

I'll add device class ID pretty soon. It is somewhat implemented in the USB layer but needs to be added to SurviveObjects proper. When I do that, I'll update the API to access that info.

**Comment by mortaas** [comment]
Thanks, I have implemented and tested the velocity and button interfaces now. The button events doesn't seem to work properly, it's currently spamming both of the button pressed and button unpressed events. Are there any particular reasons for making the axis values uint btw?

I also noticed that I am going to need some sort of device id to know which device I am updating. Alternatively, I could probably use a map from serial numbers, but if the objects are stored in a contiguous manner internally, I don't really see any reason not to use that.

The calibration works as intended. But let's say that a tracked device is obfuscated, and its position is currently flying away, then it's helpful to know that its current position is garbage (OpenVR provides this kind of functionality for instance). I also have a problem where if the tracking has lost the state of a device, it's unable to find the state of the device again. I simply have to reset the application after such a state loss.

**Comment by mortaas** [comment]
Nevermind the issues I was experiencing with the button events, it was a minor error in how I handled the null events. I am sorry if this caused you any inconveniences, I didn't really have that much time to look into it when I implemented it. Anyhow, it works like a charm now, thanks once again :)

**Pull request closed without merging**
