### PR TITLE
Adding lighthousefind_tori

### PR DESCRIPTION
**Pull request by mwturvey**
Adding a module to find the lighthouses using tori derived using the inscribed angle theorem.

### CODE REVIEW

**Comment by mwturvey** [comment]
I've finally got this cleaned up enough to submit a pull request.  Right now, finding the lighthouses is done in basically two steps.  

The first step is to get a good approximation of the lighthouse location.  This is done by generating a point cloud for each torus defined by each sensor pair and the angle between them.  Then, we take the point cloud for the torus for one sensor pair (for now, we arbitrarily pick one), and find the point in the point cloud that has the smallest least-squares distance to all of the other point clouds.   Right now, this can be tuned by changing the density of the point clouds.  The time to calculate this step increases rapidly as the number of points goes up (n^2) .  More experimentation is needed to figure out a good point cloud density, but for now it is tuned to be slower, but more reliable.

The second step is refining the point found in step 1.  Currently, this is done through a very similar approach to step 1, but using a higher density point cloud for each torus, but only drawing that point cloud near the point derived in the previous step.  

A future version of the second step will likely eliminate the point cloud altogether, and instead use a gradient descent to find the "optimal" solution.  This should be radically faster, more robust, and produce a better result.

Oh, and I'm leaking memory right now since I don't free.  I meant to fix that before pushing, but it's late and I forgot.

**Comment by cnlohr** [comment]
Errr... would you be up for merging your linear math code with the linmath.c/.h in the redist folder?  Trying to keep anything in the "tools" folder uniform.   Things like dot products, subtracting vectors, etc.  Is provided in there.  I think finding the leaks would be good but that can wait.

**Comment by mwturvey** [comment]
Yep, that was already on my "to do" list.

**Comment by cnlohr** [comment]
Would you prefer I merge now or after the use of linmath.c/.h?

**Comment by mwturvey** [comment]
I'll clean it up first.

**Comment by cnlohr** [comment]
Thanks!

**Comment by cnlohr** [comment]
Man, I can't wait to start comparing apples to apples with our lighthouse find algorithms!

**Comment by mwturvey** [comment]
So, a decent chunk of that math stuff is for doing the 3D rotation.  I took it from a stackoverflow answer, and stackoverflow shows a license of cc by-sa 3.0 (which I believe is fine).  But, I just dug further and found that code in Blender, licensed under GPL.  Interestingly, the stackoverflow poster appears to be the original author, which means that by posting to SO, he released it under cc by-sa 3.0.  Except, I'm not sure that he authored all the supporting functions that he posted, as well.  Going to dig into those, and rewrite if necessary.

**Comment by mwturvey** [comment]
Okay, I traced down the origin of all of the math library code.  Anything that wasn't clearly from the author of the stackoverflow post was thrown out and rewritten. 

In moving everything into the linmath, it was really bugging me that we can change the floating point type between single and double precision, but the functions operating were a hardcoded mixed bag of single and double precision functions, so I fixed that up so they'll all be consistent.  

I still need to update most of my new code to properly use FLT, but I think that's a task for another day.

**Comment by cnlohr** [comment]
Hmm... Most of this looks really good!  Just fyi... the FLT thing was intended to be defined tool-at-a-time.  If your tool uses doubles, then no need to use FLT.    For things like the embedded systems, they'll just say float everywhere.

Re: from author.  It looks like the code was licensed under CC2.0 BY-SA, which is incompatible with the MIT license.

**Comment by mwturvey** [comment]
Just updated a patch.  Still a WIP, not ready for review.  I will be removing all of the CC code.

The reason I'm wanting to test with FLT on a desktop is that at least one of the algorithms I've seen had anecdotal reports that the loss of precision from double to float can cause issue with really small angles.  I haven't dug deeper, but I'd rather be able to test that scenario on a desktop than run into it for the first time on an embedded platform.

**Comment by cnlohr** [comment]
Not sure if you noticed, you started reformatting the existing stuff... Also, for this project, we're doin tabs, not spaces! :-p

**Comment by cnlohr** [comment]
Also, it is DEF worth testing in both double and float to compare the differences.  You can usually learn a lot about algorithms etc by chasing down unusualities due to that.

**Comment by mwturvey** [comment]
Missed the tabs thing.  Thanks for the heads up.

**Comment by cnlohr** [comment]
I'm gonna try to make time to test everything tonight.  Everything looks great, but will double-check.  I can't wait to get to the point where we can compare solutions by finding how well the results line up!

**Comment by cnlohr** [comment]
All data looks great!  Thanks!  It's now in mainline.

**Pull request merged**
