### PR TITLE
disambiguator

### PR DESCRIPTION
**Pull request by jpicht**
I finally was able to take the time to document and fix my implementation of the disambiguator. It is not currently enabled by default.

I also added a comment about the "theory" behind it on top of the `disambiguator.c` file.

### CODE REVIEW

**Comment by cnlohr** [comment]
eish... can you check this against my current branch?

**Comment by cnlohr** [comment]
Also, @jpicht are you in discord?

**Comment by cnlohr** [comment]
@jpicht I tried using it and it's working slightly better now, but not as well as mine is currently working :-/ 

Just wondering, do you have a vive?

**Comment by jpicht** [comment]
Just joined the discord thingy.

I still don't have a vive, but now it is available in a shop, that is like ten minutes from where I live ... uhm ...

**Comment by cnlohr** [comment]
Don't rush things too much.  My disambiguator is good enough "for now" but it does have a lot of limitations and doesn't perform well when you get within 1m of the lighthouse.  I think this is the sort of thing that takes a lot of fooling around with with the real system to finesse into something great.

**Pull request merged**
